/**
 * Generates the `index.js` loader that `zignapi build` writes next to the
 * addon. The loader is **standalone** (no dependency on zignapi at runtime): it
 * detects the running platform, resolves the right binary, and re-exports the
 * addon's API (hiding the embedded `__zignapi_dts__`).
 *
 * Resolution order:
 *   1. a local `./<binary>.node`                    — the dev build at the root
 *   2. a local `./npm/<triple>/<binary>.<triple>.node` — an in-tree per-platform build
 *   3. the `<packageName>-<triple>` package          — the published per-platform package
 *   4. otherwise a clear error listing supported triples and what was tried
 *
 * Steps 1–2 make dev transparent (identical to loading the raw `.node`); step 3
 * is production; step 4 is a good failure message instead of a cryptic MODULE
 * NOT FOUND.
 */
export interface LoaderOptions {
  /** The `.node` base name (e.g. "zparse"). */
  binaryName: string;
  /** The full npm name incl. scope; platform packages are `<packageName>-<triple>`. */
  packageName: string;
  /** Supported triples (for the error message and package ids). */
  targets: string[];
}

export function generateLoader(opts: LoaderOptions): string {
  const data = JSON.stringify({
    binary: opts.binaryName,
    pkg: opts.packageName,
    triples: opts.targets,
  });
  return `"use strict";
// Generated by zignapi — do not edit.
// Standalone multi-platform loader: resolves the native addon for this platform.
const { join } = require("node:path");
const { binary: BINARY, pkg: PKG, triples: TRIPLES } = ${data};

// glibc vs musl on linux, with no external dependency: the process report
// exposes the runtime glibc version only on a glibc system.
function libc() {
  if (process.platform !== "linux") return null;
  try {
    const report = process.report.getReport();
    return report && report.header && report.header.glibcVersionRuntime ? "gnu" : "musl";
  } catch {
    return "gnu";
  }
}

// The napi-rs triple for the running platform.
function currentTriple() {
  const arch = process.arch;
  if (process.platform === "darwin") return "darwin-" + arch;
  if (process.platform === "win32") return "win32-" + arch + "-msvc";
  if (process.platform === "linux") return "linux-" + arch + "-" + libc();
  return process.platform + "-" + arch;
}

const triple = currentTriple();
const tried = [];
let addon = null;

// 1–2. local binaries: the dev build at the root, then an in-tree per-platform
// build (named with the triple, like the published one).
const locals = [
  join(__dirname, BINARY + ".node"),
  join(__dirname, "npm", triple, BINARY + "." + triple + ".node"),
];
for (const path of locals) {
  try {
    addon = require(path);
    break;
  } catch (err) {
    tried.push(path + " (" + (err.code || err.message) + ")");
  }
}

// 3. the published per-platform package: <packageName>-<triple>.
if (!addon) {
  const id = PKG + "-" + triple;
  try {
    addon = require(id);
  } catch (err) {
    tried.push(id + " (" + (err.code || err.message) + ")");
  }
}

if (!addon) {
  throw new Error(
    "zignapi: no native binary for platform '" + triple + "'.\\n" +
      "Supported: " + TRIPLES.join(", ") + ".\\n" +
      "Tried:\\n  " + tried.join("\\n  "),
  );
}

const { __zignapi_dts__, ...api } = addon;
module.exports = api;
`;
}

/**
 * The public Node entry (`index.js`): a thin re-export of the native loader.
 * Keeping it separate from `bindings.js` mirrors napi-rs's layout and lets the
 * package.json `exports` map route `node` → here and `browser` → `wasm.js`,
 * while `require("pkg/bindings.js")` stays available to force the native path.
 */
export function generateIndexEntry(): string {
  return `"use strict";
// Generated by zignapi — public entry. Re-exports the native backend.
module.exports = require("./bindings.js");
`;
}

/** The `wasm.d.ts` alias — never a copy, so the types can't diverge. */
export function generateWasmDts(): string {
  return `// Generated by zignapi — types alias (single source: index.d.ts).\nexport * from "./index.js";\n`;
}

export interface WasmGlueOptions {
  /** Per-function decode strategy, from the wasm `__zignapi_meta` blob. */
  returns: Record<string, string>;
  /** Module constants to expose alongside the functions. */
  consts: Record<string, unknown>;
  /** The `.wasm` bytes, base64-encoded (embedded for a fully-sync, self-contained,
   * bundler-friendly module — same synchronous API as the native backend). */
  wasmBase64: string;
}

/**
 * The WASM glue (`wasm.js`): a UMD module exposing the **same synchronous API**
 * as the native `index.js`. It decodes the embedded module, instantiates it
 * lazily and synchronously (Node and browser alike — no async init, no fetch),
 * and per call: encodes the input into linear memory, invokes the export,
 * re-throws a real `Error` on failure, and decodes the result per its declared
 * kind (raw string / number / boolean / JSON.parse). The API-identity is the
 * absolute criterion: the same user code runs on both backends.
 */
export function generateWasmGlue(opts: WasmGlueOptions): string {
  const data = JSON.stringify({ returns: opts.returns, consts: opts.consts });
  return `// Generated by zignapi — WASM backend. Same (synchronous) API as index.js.
(function (root, factory) {
  if (typeof module === "object" && module.exports) module.exports = factory();
  else root.zignapi = factory();
})(typeof self !== "undefined" ? self : this, function () {
  "use strict";
  var META = ${data};
  var WASM_BASE64 = "${opts.wasmBase64}";

  var ex = null;
  function bytes() {
    if (typeof Buffer !== "undefined") return Buffer.from(WASM_BASE64, "base64");
    var bin = atob(WASM_BASE64), out = new Uint8Array(bin.length);
    for (var i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
    return out;
  }
  // Lazy + SYNCHRONOUS instantiation (WebAssembly.Module/Instance are sync).
  function inst() {
    if (ex) return ex;
    ex = new WebAssembly.Instance(new WebAssembly.Module(bytes()), {}).exports;
    return ex;
  }

  var enc = new TextEncoder(), dec = new TextDecoder();
  function call(name, input) {
    var e = inst();
    // The ABI passes the input as (ptr, len) in linear memory. Re-read
    // memory.buffer after every call that can grow memory (it detaches views).
    var buf = enc.encode(String(input));
    var p = e.__zignapi_alloc(buf.length);
    new Uint8Array(e.memory.buffer).set(buf, p);
    var packed = e[name](p, buf.length);
    var elen = e.__zignapi_err_len();
    if (elen > 0) {
      var ep = e.__zignapi_err_ptr();
      throw new Error(dec.decode(new Uint8Array(e.memory.buffer, ep, elen)));
    }
    var ptr = Number(packed >> 32n), len = Number(packed & 0xffffffffn);
    var raw = dec.decode(new Uint8Array(e.memory.buffer, ptr, len));
    var kind = META.returns[name];
    if (kind === "string") return raw;
    if (kind === "number") return Number(raw);
    if (kind === "boolean") return raw === "true";
    if (kind === "void") return undefined;
    return JSON.parse(raw);
  }

  var api = {};
  Object.keys(META.returns).forEach(function (name) {
    api[name] = function (input) { return call(name, input); };
  });
  Object.keys(META.consts).forEach(function (name) { api[name] = META.consts[name]; });
  return api;
});
`;
}
